[2024-07-03T05:10:53.524+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:10:53.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:10:53.527+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:10:53.526+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:10:53.547+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:10:53.543+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:10:53.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:10:53.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.046 seconds
[2024-07-03T05:11:23.765+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:11:23.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:11:23.767+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:11:23.767+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:11:23.803+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:11:23.797+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:11:23.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:11:23.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.082 seconds
[2024-07-03T05:11:54.015+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:11:54.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:11:54.018+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:11:54.017+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:11:54.042+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:11:54.038+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:11:54.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:11:54.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.053 seconds
[2024-07-03T05:12:24.308+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:12:24.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:12:24.310+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:12:24.310+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:12:24.331+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:12:24.328+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:12:24.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:12:24.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.045 seconds
[2024-07-03T05:12:54.567+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:12:54.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:12:54.569+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:12:54.568+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:12:54.599+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:12:54.593+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:12:54.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:12:54.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.059 seconds
[2024-07-03T05:13:24.810+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:13:24.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:13:24.812+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:13:24.812+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:13:24.829+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:13:24.824+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:13:24.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:13:24.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.046 seconds
[2024-07-03T05:13:55.130+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:13:55.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:13:55.133+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:13:55.133+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:13:55.164+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:13:55.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:13:55.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:13:55.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.061 seconds
[2024-07-03T05:14:25.334+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:14:25.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:14:25.337+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:14:25.336+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:14:25.365+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:14:25.361+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:14:25.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:14:25.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.052 seconds
[2024-07-03T05:14:55.641+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:14:55.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:14:55.643+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:14:55.642+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:14:55.678+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:14:55.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:14:55.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:14:55.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.065 seconds
[2024-07-03T05:15:25.898+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:15:25.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:15:25.900+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:15:25.900+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:15:25.933+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:15:25.926+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:15:25.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:15:25.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.064 seconds
[2024-07-03T05:15:56.205+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:15:56.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:15:56.207+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:15:56.207+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:15:56.236+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:15:56.228+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:15:56.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:15:56.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.061 seconds
[2024-07-03T05:16:26.430+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:16:26.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:16:26.433+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:16:26.433+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:16:26.457+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:16:26.453+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:16:26.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:16:26.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.049 seconds
[2024-07-03T05:16:56.688+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:16:56.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:16:56.690+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:16:56.689+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:16:56.705+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:16:56.702+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:16:56.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:16:56.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.048 seconds
[2024-07-03T05:17:26.993+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:17:26.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_ana;ysis.py for tasks to queue
[2024-07-03T05:17:26.995+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:17:26.995+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:17:27.027+0000] {logging_mixin.py:188} INFO - [2024-07-03T05:17:27.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_ana;ysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_ana;ysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-07-03T05:17:27.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_ana;ysis.py
[2024-07-03T05:17:27.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_ana;ysis.py took 0.064 seconds
